name: deploy prd

on:
  workflow_run:
    workflows:
      - test
    types:
      - completed
    branches:
      - master

jobs:
  git_status:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - run: git status
