name: on push

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  git_status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git status
