name: on push

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  git_status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git status

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - run: docker images
      - run: docker buildx build --no-cache -t megane42/test -o type=docker .
      - run: docker images
