name: test

on:
  pull_request:
    paths-ignore:
      - 'infrastructure/**'
  push:
    branches:
      - develop
      - master

jobs:
  git_status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git status
